---
title: "`Static plots`"
author: "Chris Hamm"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center", cache = TRUE)
options(dplyr.width = Inf)
```




## Preliminaries

```{r preliminaries, echo = TRUE}
set.seed(923741)

library("tidyverse")
library("gganimate")
```



## Load data
```{r irisData}
data(iris) # load the iris data
glimpse(iris) # view the data
```


## Static plot
Now create the static plot. Add any plot aesthetics at this point.
```{r irisStatic}
iris %>% 
  ggplot(aes(x = Petal.Width, y= Petal.Length, show.legend = FALSE)) +
  geom_point(size = 5, alpha = 0.75)
```

I like to build my plots step-by-step, so I save them as objects once I get them looking as I want. 

Adding colors will force the plot to be "choppy."

```{r irisSaved}
iris_plot <- iris %>% 
  ggplot(aes(x = Petal.Width, y= Petal.Length)) +
  geom_point(size = 5, alpha = 0.75, show.legend = FALSE) +
  labs(x = "Petal width", y = "Petal length")
```
